openapi: 3.1.0
info:
  title: Nuclei Agent API
  version: '1.0'
  description: Nuclei Agent API for Cloud
  summary: Nuclei Agent API for Cloud
  contact:
    name: Projectdiscovery
    url: 'https://projectdiscovery.io'
    email: contact@projectdiscovery.io
  license:
    name: MIT
    identifier: MIT
servers:
  - url: 'http://localhost:8087' 
paths:
  /v1/scans:
    post:
      summary: Create Scan
      tags:
        - scans
      operationId: post-v1-scans
      responses:
        '200':
          $ref: '#/components/responses/TriggerUserScanResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      description: Trigger a scan
      security:
        - X-API-Key: []
      requestBody:
        $ref: '#/components/requestBodies/TriggerUserScanRequest'
      parameters: []
  '/v1/scans/{scan_id}':
    parameters:
      - schema:
          type: string
        name: scan_id
        in: path
        required: true
    get:
      summary: Get Scan
      tags:
        - scans
      responses:
        '200':
          $ref: '#/components/responses/GetScanDetailsResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '499':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: get-v1-scans-scan_id
      description: Get details of a scan by scan ID
      security:
        - X-API-Key: []
  /v1/agents:
    post:
      summary: Register Local Agent
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                  - id
                properties:
                  ok:
                    type: boolean
                  id:
                    type: string
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: post-agent-register
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - machine_id
                - cpu_cores
                - memory_gb
                - os
                - arch
                - hostname
              properties:
                machine_id:
                  type: string
                cpu_cores:
                  type: integer
                memory_gb:
                  type: integer
                os:
                  type: string
                arch:
                  type: string
                hostname:
                  type: string
    parameters: []
    get:
      summary: Get Local Agents
      tags:
        - agents
      responses:
        '200':
          $ref: '#/components/responses/GetAgents'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: get-agents
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
            maximum: 10
            minimum: 1
          description: The numbers of items to return
        - in: query
          name: status
          schema:
            type: string
            enum:
              - active
              - inactive
              - idle
  '/agents/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get local agent
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalAgent'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: get-agents-id
      parameters: []
    delete:
      summary: Deregister local agent
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                properties:
                  ok:
                    type: boolean
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: delete-agents-id
      parameters: []
  '/agents/{id}/poll':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Poll Agent Tasks
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgentPollTask'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: get-agents-id-poll
      parameters:
        - schema:
            type: integer
          in: query
          name: count
  '/agents/{id}/ack':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Acknowledge Agent Tasks
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                properties:
                  ok:
                    type: boolean
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: post-agents-id-ack
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                $ref: '#/components/schemas/AgentAckRequest'
  '/agents/{id}/results':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Submit Agent Results
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                properties:
                  ok:
                    type: boolean
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: post-agents-id-results
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: byte
  '/agents/{id}/ping':
    post:
      summary: Ping Agent Endpoint
      tags:
        - agents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                properties:
                  ok:
                    type: boolean
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      operationId: post-agents-id-ping
      parameters: []
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas:
    LocalAgent:
      title: LocalAgent
      type: object
      required:
        - id
        - machine_id
        - cpu_cores
        - memory_gb
        - os
        - arch
        - hostname
        - last_ping_at
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
        machine_id:
          type: string
        cpu_cores:
          type: integer
        memory_gb:
          type: integer
        os:
          type: string
        arch:
          type: string
        last_ping_at:
          type: string
          format: date-time
        hostname:
          type: string
        status:
          enum:
            - active
            - inactive
            - idle
        uptime:
          type: string
          format: duration
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ScanStatusItem:
      title: ScanStatusItem
      type: object
      required:
        - scan_id
        - status
        - scan_time_elapsed
        - progress
        - failure_reason
        - created_at
        - updated_at
        - total_target
        - completed_at
        - total_scan
        - total_template
        - name
        - is_oss
        - is_cloud
      properties:
        scan_id:
          type: string
        status:
          type: string
        scan_time_elapsed:
          type: string
        progress:
          type: integer
        failure_reason:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        total_target:
          type: integer
        completed_at:
          type: string
        total_scan:
          type: integer
        total_template:
          type: integer
        name:
          type: string
        severity:
          type: object
        is_oss:
          type: boolean
        is_cloud:
          type: boolean
        asset_ids:
          type: array
          items:
            type: string
        is_rescan:
          type: boolean
        public_templates:
          type: array
          items:
            type: string
        report_config_ids:
          type: array
          items:
            type: string
        rescan_count:
          type: integer
        scan_config_ids:
          type: array
          items:
            type: string
        template_ids:
          type: array
          items:
            type: string
        template_urls:
          type: array
          items:
            type: string
        schedule:
          type: object
    AgentPollTask:
      title: AgentPollTask
      type: object
      properties:
        id:
          type: string
        value:
          type: string
          format: byte
        scan_id:
          type: string
        scan_config:
          type: string
        reporting_config:
          type: string
      required:
        - id
        - value
        - scan_id
    AgentAckRequest:
      title: AgentAckRequest
      type: object
      properties:
        id:
          type: string
        scan_id:
          type: string
      required:
        - id
        - scan_id
  securitySchemes:
    APIKey:
      type: apiKey
      in: header
      name: X-API-Key
  requestBodies:
    TriggerUserScanRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              targets:
                type: array
                items:
                  type: string
              templates:
                type: array
                items:
                  type: string
              assets:
                type: array
                items:
                  type: string
              private_templates:
                type: array
                items:
                  type: object
              name:
                type: string
              recommended:
                type: boolean
              all:
                type: boolean
              alerting_config_ids:
                type: array
                items:
                  type: string
              scan_config_ids:
                type: array
                items:
                  type: string
              reporting_config_ids:
                type: array
                items:
                  type: string
              early_templates:
                type: array
                items:
                  type: string
              exclude_targets:
                type: array
                items:
                  type: string
              enumeration_ids:
                type: array
                items:
                  type: object
              schedule_only:
                type: boolean
              disable_global_alert_config:
                type: boolean
              disable_global_report_config:
                type: boolean
              disable_global_scan_config:
                type: boolean
  responses:
    GetAgents:
      description: Get Agents Response
      content:
        application/json:
          schema:
            type: object
            required:
              - current_page
              - result_count
              - total_results
              - total_pages
              - data
            properties:
              current_page:
                type: integer
              result_count:
                type: integer
              total_results:
                type: integer
              total_pages:
                type: integer
              data:
                type: array
                items:
                  $ref: '#/components/schemas/LocalAgent'
    GetScanDetailsResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ScanStatusItem'
    TriggerUserScanResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              message:
                type: string
            required:
              - message
    ErrorResponse:
      description: Bad request error response
      content:
        application/json:
          schema:
            type: object
            properties:
              kind:
                type: string
              param:
                type: string
              code:
                type: string
              error_id:
                type: string
              error:
                type: string
              message:
                type: string
              status:
                type: integer
            required:
              - kind
              - code
              - message
              - status