id: iterate-values-flow-parallel

info:
  name: Extract Email IDs from Response
  author: pdteam
  severity: info


### this is parallel version of iterate-values-flow.yaml where requests are sent in parallel

flow: http(0) || http(1)

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        name: emails
        internal: true
        regex:
          - '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

  - method: GET
    path:
      - "{{BaseURL}}/user/{{email}}"

    payloads:
      email: "{{emails}}"
  
    matchers:
      - type: word
        words:
          - "Welcome"