name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

#      - name: Test
#        run: go test ./...
#        working-directory: v2/

      - name: Integration Tests
        id: integrationTests
        run: bash run.sh
        working-directory: integration_tests/

      - name: Re-run Integration Tests in Debug Mode
        if: ${{ failure() }}
#        if: steps.integrationTests.result == 'failure'
        env:
          DEBUG: true
          GH_ACTION: true
        run: bash run.sh
        working-directory: integration_tests/

      # At the bottom for known issue on OSX - https://github.com/projectdiscovery/nuclei/issues/1309
      - name: Race Condition Tests
        run: go build -race .
        working-directory: v2/cmd/nuclei/
