name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Debug
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Integration Tests
        env:
          GH_ACTION: true
        run: |
          chmod +x run.sh
          bash run.sh ${{ matrix.os }}
        working-directory: integration_tests/

      - name: Race Condition Tests
        if: ${{ matrix.os != 'windows-latest' }} # known issue: https://github.com/golang/go/issues/46099
        run: go run . -tud /tmp && go run -race . -u scanme.sh
        working-directory: v2/cmd/nuclei/