name: SBOM-Dependency

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up curl
        run: sudo apt-get install -y curl

      - name: Run curl command and save response to file
        run: |
          response=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/rahiCICD/nuclei/dependency-graph/sbom")
          echo "$response" > sbom.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with the desired Python version

      - name: Convert SBOM to CSV
        run: |
          python - <<EOF
          import os
          import json
          import csv

         
