name: Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl -y

      - name: Generate SBOM
        run: |
          # Octokit.js code
          # Replace '', 'rahiCICD', and 'nuclei' with the actual values
          curl -X GET \
            -H "Authorization: token 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" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/rahiCICD/nuclei/dependency-graph/sbom" \
            -o sbom.txt

      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: sbom.json
