name: SBOM-Dependepncy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up curl
        run: sudo apt-get install -y curl

      - name: Run curl command
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rahiCICD/nuclei/dependency-graph/sbom > nuclei-sbom.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: curl-output
          path: nuclei.json
