name: Download and Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  download-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SBOM
        run: |
          # Install curl
          sudo apt-get update
          sudo apt-get install -y curl

          # Download SBOM using curl
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o sbom.txt \
            https://github.com/rahiCICD/nuclei/dependency-graph/sbom

      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: sbom.txt
