name: Export SBOM

on:
  push:
    branches:
      - main

jobs:
  export_sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Export SBOM
        run: |
          python -c "import requests, json; owner = 'rahiCICD'; repo = 'nuclei'; token = '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'; url = f'https://api.github.com/repos/{owner}/{repo}/dependency-graph/sbom'; headers = {{'Authorization': f'Bearer {token}', 'Accept': 'application/vnd.github.hawkgirl-preview+json'}}; response = requests.get(url, headers=headers); response.raise_for_status(); sbom = response.json().get('sbom', {}); with open('sbom.json', 'w') as file: json.dump(sbom, file, indent=4); print('SBOM exported successfully.')"

      - name: Convert JSON to CSV
        run: |
          python -c "import json, csv; with open('sbom.json') as file: data = json.load(file); packages = data.get('packages', []); with open('sbom.csv', mode='w', newline='') as file: writer = csv.writer(file); writer.writerow(['Package ID', 'Package Name', 'Version', 'Download Location', 'License Declared', 'Files Analyzed', 'Supplier']); for package in packages: writer.writerow([package.get('SPDXID', 'NOASSERTION'), package.get('name', 'NOASSERTION'), package.get('versionInfo', 'NOASSERTION'), package.get('downloadLocation', 'NOASSERTION'), package.get('licenseDeclared', 'NOASSERTION'), package.get('filesAnalyzed', False), package.get('supplier', 'NOASSERTION')]); print('JSON data converted to CSV successfully!')"

      - name: Upload SBOM CSV
        uses: actions/upload-artifact@v2
        with:
          name: sbom-csv
          path: sbom.csv
