name: 🛠 Template Validate

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: 1.18

      - name: Setup Nuclei
        run: |
          curl --silent "https://api.github.com/repos/projectdiscovery/nuclei/releases/latest" | jq -r .tag_name | xargs -I {} echo TAG={} >> $GITHUB_OUTPUT
          wget -q https://github.com/projectdiscovery/nuclei/releases/download/${TAG}/nuclei_${TAG:1}_linux_amd64.zip
          sudo unzip nuclei*.zip -d /usr/local/bin
        working-directory: /tmp

      - name: Template Validation
        run: |
          nuclei -validate
          nuclei -validate -w ./workflows